##### 1. Импортируйте библиотеку Numpy и дайте ей псевдоним np. Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй — числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец — это признак, а строка — наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [11]:
import numpy as np

##### Создаем массив

In [12]:
a = np.array(([1, 2, 3, 3, 1], [6, 8, 11, 10, 7]), int)
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

##### Транспонируем матрицу

In [13]:
a = np.transpose(a)
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

##### Вычисляем среднее по каждому столбцу

In [161]:
mean_a = np.mean(a,axis = 0)
mean_a

array([2. , 8.4])

##### 2. Вычислите массив a_centered, отняв от значений массива а средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [16]:
a_centered = np.subtract(a,mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

##### 3. Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N — число наблюдений.

In [17]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]
a_centered_sp

8.0

##### Функция  shape возвращает нам кол-во строк

In [18]:
a_centered_sp/(a.shape[0]-1)

2.0

##### 4. Число, которое мы получили в конце задания 3, является ковариацией двух признаков, содержащихся в массиве а. В задании 3 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации. Подробнее узнать о ковариации можно здесь: https://studopedia.ru/9_153900_viborochnaya-kovariatsiya-i-viborochnaya-dispersiya.html В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом — с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив a. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [19]:
np.cov(np.transpose(a))[0,1]

2.0

##### 5. Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский']. Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные: [1, 1, 1, 2, 2, 3, 3], ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], [450, 300, 350, 500, 450, 370, 290].

In [20]:
import pandas as pd

In [21]:
authors = pd.DataFrame(
    {'author_id':[1, 2, 3],
    'author_name':['Тургенев', 'Чехов', 'Островский']},
    columns = ['author_id','author_name'])
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [22]:
book = pd.DataFrame(
    {'author_id':[1, 1, 1, 2, 2, 3, 3],
    'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    'price':[450, 300, 350, 500, 450, 370, 290]}
    ,columns = ['author_id','book_title','price'])
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

##### 6. Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [23]:
authors_price = pd.merge(authors,book,on = 'author_id', how = 'right')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

##### 7. Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

##### Способ №1

In [24]:
top5 = authors_price.sort_values(by = 'price', ascending = False).reset_index(drop = True)[:5]
top5

author_id author_name         book_title  price
0          2       Чехов   Толстый и тонкий    500
1          1    Тургенев        Отцы и дети    450
2          2       Чехов    Дама с собачкой    450
3          3  Островский              Гроза    370
4          1    Тургенев  Дворянское гнездо    350

##### Способ 2

In [25]:
top5_2 = authors_price.sort_values(by = 'price', ascending = False).reset_index(drop = True).head(5)
top5_2

author_id author_name         book_title  price
0          2       Чехов   Толстый и тонкий    500
1          1    Тургенев        Отцы и дети    450
2          2       Чехов    Дама с собачкой    450
3          3  Островский              Гроза    370
4          1    Тургенев  Дворянское гнездо    350

##### 8. Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца: author_name, min_price, max_price и mean_price, в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.

##### Обращаение к столблу датафрейма разными способами

In [73]:
%%timeit
authors_price['author_name']


1.34 µs ± 17.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [74]:
%%timeit
authors_price.loc[:,'author_name']

24.5 µs ± 337 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [75]:
%%timeit
authors_price.iloc[:,1]

41.2 µs ± 1.17 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


##### Исходя из статистики выполнения способ №1 является самым быстрым.

##### Сделаем группировку по полю автора и посчитаем аггрегаты над этой группировкой.

In [158]:
authors_stat = authors_price[['author_name','price']].groupby('author_name').agg([('min_price','min'), ('max_price','max'), ("mean_price", 'mean')])

##### т.к. в предыдущем действии мы получили мульти индекс, мы удаляем первый уровень из мульти индекса

In [159]:
authors_stat.columns = authors_stat.columns.droplevel([0])

##### Теперь нам надо перевести названия на уровень названия колонок. Для этого му убираем строковый индекс по полю автора и добавляем новый.

In [160]:
authors_stat.reset_index(0)

author_name  min_price  max_price  mean_price
0  Островский        290        370  330.000000
1    Тургенев        300        450  366.666667
2       Чехов        450        500  475.000000

##### *9.1 Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги — твердая или мягкая. В этот столбец поместите данные из следующего списка: ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']. 
##### 9.2 Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака. 
##### 9.3 Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться «твердая» и «мягкая», а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy. 
##### 9.4 Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. 
##### 9.5 Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.




##### *9.1 Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги — твердая или мягкая. В этот столбец поместите данные из следующего списка: ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']. 

In [181]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

##### 9.2 Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака. 

In [182]:
?pd.pivot_table

##### 9.3 Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться «твердая» и «мягкая», а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy. 

In [183]:
book_info = pd.pivot_table(authors_price, values = 'price', index=['author_name'], columns=['cover'], aggfunc=np.sum, fill_value=0)
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

##### 9.4 Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. 

In [184]:
book_info.to_pickle('./book_info.pkl')
book_info2 = pd.read_pickle('./book_info.pkl')
book_info2

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

##### 9.5 Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.

In [179]:
book_info2.equals(book_info)

True